import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "První stránka s NEXT JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

//in default all components in App folder are react sever side components, because it is faster
//if you want to change it to client side coomponent you need to add to the top of your page "use client"
//if you use hooks you need to have client side component with "use client"
